### ISSUE TITLE
Duvida | Docker + PM2

### ISSUE THREAD

**Issue by pabloalmeidas13** [ErickWendel/nodejs-microservicos-docker#1]
Blz Erick,
achei bacana essa proposta de microserviços,
porem fiquei curioso se é um boa pratica ultilizar PM2 dentro do docker?

outra duvida,
voce acha melhor ultilizar o pm2 dentro do docker 
pelo fato de facilitar rodar o node em modo cluster?

Vlw!!

**Comment by ErickWendel** [comment]
Cara depende muito! 
Eu sempre coloco o pm2 dentro do docker, pelos seguintes motivos: 
Nem sempre estamos usando um orquestrador de containers (caso uma interrupção restartar o serviço), se nao tiver o pm2, ele vai quebrar e nao subir mais. 
Por padrão o pm2 tenta umas 3 vezes, caso a aplicação realmente estiver danificada ele derruba o serviço e para tudo.

para clusters, eu prefiro usar cluster de serviços (ex. usar um kubernetes ou docker-swarm). Para rodar no container, eu uso o pm2-docker só para manipular algo inesperado e fazer pelo menos os 3 restarts sem que a aplicação se encerre :shipit: 

Respondido ? hehe

**Comment by pabloalmeidas13** [comment]
Opa !! Super respondido! kkk
vlw mesmo!! 
vou seguir nesta linha e ver como fica,!
